// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/myml/web-file-manager/internal/controller"
	"github.com/myml/web-file-manager/internal/handle"
	"github.com/myml/web-file-manager/internal/mfs"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*gin.Engine, error) {
	fs, err := uiFS()
	if err != nil {
		return nil, err
	}
	rootDIR := rootDir()
	aferoFs := mfs.RootFS(rootDIR)
	moveF := handle.Move(aferoFs)
	downloadF := handle.Download(aferoFs)
	listF := handle.List(aferoFs)
	uploadF := handle.Upload(aferoFs)
	mkdirF := handle.Mkdir(aferoFs)
	deleteF := handle.Delete(aferoFs)
	copyFileF := handle.CopyFile(aferoFs)
	api := controller.API{
		MoveF:     moveF,
		DownloadF: downloadF,
		ListF:     listF,
		UploadF:   uploadF,
		MkdirF:    mkdirF,
		DeleteF:   deleteF,
		CopyFileF: copyFileF,
	}
	engine := controller.NewEngine(fs, api)
	return engine, nil
}
